### ISSUE TITLE
Add difficulty check in validate block

### ISSUE THREAD

**Issue by srijal30** [srijal30/ConCurrency#4]
We need a way to check for proof-of-work

**Comment by CytaStorm** [comment]
Isn't the hash itself the proof of work?

**Comment by srijal30** [comment]
> Isn't the hash itself the proof of work?

Yea but we need a way to validate that proof of work in the validate_block method by checking if the number of zeroes is correct

**Comment by srijal30** [comment]
Added in commit https://github.com/srijal30/ConCurrency/commit/a2b17d608b7d982c669f80b5a0e6107054a5036a
