### ISSUE TITLE
How Will The Blockchain Start?

### ISSUE THREAD

**Issue by srijal30** [srijal30/ConCurrency#5]
Will there be a genesis block? How will the first miners mine blocks if there are no transactions? How will the miners slowly build up their balance?

**Comment by CytaStorm** [comment]
I believe there should be a genesis block that acts like a "bank" that hands out coins

**Comment by srijal30** [comment]
specify your thoughts

**Comment by CytaStorm** [comment]
Let's reserve a pub/priv key as the "bank" and give it however many coins we want in total, and then have that block do the transaction to one of us, and that will act as the first transaction.
